ccflags-y += -I$(srctree)/drivers/spi/mediatek/mt6755

obj-y	+= fingerprint.o

obj-$(CONFIG_FINGERPRINT_SUNWAVE_9551)	+=  sunwave9551_fp/
obj-$(CONFIG_FINGERPRINT_GF3208_GOODIX)	+=  gf3208_goodix/
obj-$(CONFIG_FINGERPRINT_GFX1XM_GOODIX)	+=  gfx1xm/
obj-$(CONFIG_FINGERPRINT_CS15XX)	+=  cs15xx/
obj-$(CONFIG_FINGERPRINT_MICROARRAY)	+=  microarray_v4.0.01/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF5216)	+=  goodix_gf5216/
obj-$(CONFIG_FINGERPRINT_SUNWAVECORP)	+=  sunwavecorp/

